(function(c){var b={init:function(a){return this.each(function(){b.destroy.call(this);this.opt=c.extend(!0,{},c.fn.raty.defaults,a);var d=c(this);b._callback.call(this,["number","readOnly","score","scoreName"]);this.opt.precision&&b._adjustPrecision.call(this);this.opt.number=b._between(this.opt.number,0,this.opt.numberMax);this.opt.path=this.opt.path||"";this.opt.path&&"/"!==this.opt.path.slice(this.opt.path.length-1,this.opt.path.length)&&(this.opt.path+="/");this.stars=b._createStars.call(this);
this.score=b._createScore.call(this);b._apply.call(this,this.opt.score);var f=this.opt.space?4:0,e=this.opt.width||this.opt.number*this.opt.size+this.opt.number*f;this.opt.cancel&&(this.cancel=b._createCancel.call(this),e+=this.opt.size+f);this.opt.readOnly?b._lock.call(this):(d.css("cursor","pointer"),b._binds.call(this));!1!==this.opt.width&&d.css("width",e);b._target.call(this,this.opt.score);d.data({settings:this.opt,raty:!0})})},_adjustPrecision:function(){this.opt.targetType="score";this.opt.half=
!0},_apply:function(a){a&&0<a&&(a=b._between(a,0,this.opt.number),this.score.val(a));b._fill.call(this,a);a&&b._roundStars.call(this,a)},_between:function(a,d,b){return Math.min(Math.max(parseFloat(a),d),b)},_binds:function(){this.cancel&&b._bindCancel.call(this);b._bindClick.call(this);b._bindOut.call(this);b._bindOver.call(this)},_bindCancel:function(){b._bindClickCancel.call(this);b._bindOutCancel.call(this);b._bindOverCancel.call(this)},_bindClick:function(){var a=this,d=c(a);a.stars.on("click.raty",
function(b){a.score.val(a.opt.half||a.opt.precision?d.data("score"):this.alt);a.opt.click&&a.opt.click.call(a,parseFloat(a.score.val()),b)})},_bindClickCancel:function(){var a=this;a.cancel.on("click.raty",function(d){a.score.removeAttr("value");a.opt.click&&a.opt.click.call(a,null,d)})},_bindOut:function(){var a=this;c(this).on("mouseleave.raty",function(d){var c=parseFloat(a.score.val())||void 0;b._apply.call(a,c);b._target.call(a,c,d);a.opt.mouseout&&a.opt.mouseout.call(a,c,d)})},_bindOutCancel:function(){var a=
this;a.cancel.on("mouseleave.raty",function(d){c(this).attr("src",a.opt.path+a.opt.cancelOff);a.opt.mouseout&&a.opt.mouseout.call(a,a.score.val()||null,d)})},_bindOverCancel:function(){var a=this;a.cancel.on("mouseover.raty",function(d){c(this).attr("src",a.opt.path+a.opt.cancelOn);a.stars.attr("src",a.opt.path+a.opt.starOff);b._target.call(a,null,d);a.opt.mouseover&&a.opt.mouseover.call(a,null)})},_bindOver:function(){var a=this,d=c(a);a.stars.on(a.opt.half?"mousemove.raty":"mouseover.raty",function(f){var e=
parseInt(this.alt,10);if(a.opt.half){var g=parseFloat((f.pageX-c(this).offset().left)/a.opt.size),h=0.5<g?1:0.5,e=e-1+h;b._fill.call(a,e);a.opt.precision&&(e=e-h+g);b._roundStars.call(a,e);d.data("score",e)}else b._fill.call(a,e);b._target.call(a,e,f);a.opt.mouseover&&a.opt.mouseover.call(a,e,f)})},_callback:function(a){for(i in a)"function"===typeof this.opt[a[i]]&&(this.opt[a[i]]=this.opt[a[i]].call(this))},_createCancel:function(){var a=c(this),d=c("<img />",{src:this.opt.path+this.opt.cancelOff,
alt:"x",title:this.opt.cancelHint,"class":"raty-cancel"});"left"==this.opt.cancelPlace?a.prepend("&#160;").prepend(d):a.append("&#160;").append(d);return d},_createScore:function(){return c("<input />",{type:"hidden",name:this.opt.scoreName}).appendTo(this)},_createStars:function(){for(var a=c(this),d=1;d<=this.opt.number;d++){var f=b._getHint.call(this,d),e=this.opt.score&&this.opt.score>=d?"starOn":"starOff",e=this.opt.path+this.opt[e];c("<img />",{src:e,alt:d,title:f}).appendTo(this);this.opt.space&&
a.append(d<this.opt.number?"&#160;":"")}return a.children("img")},_error:function(a){c(this).html(a);c.error(a)},_fill:function(a){for(var d=0,b=1;b<=this.stars.length;b++){var c=this.stars.eq(b-1),g=this.opt.single?b==a:b<=a;if(this.opt.iconRange&&this.opt.iconRange.length>d){var h=this.opt.iconRange[d],j=h.on||this.opt.starOn,k=h.off||this.opt.starOff,g=g?j:k;b<=h.range&&c.attr("src",this.opt.path+g);b==h.range&&d++}else g=g?"starOn":"starOff",c.attr("src",this.opt.path+this.opt[g])}},_getHint:function(a){var b=
this.opt.hints[a-1];return""===b?"":b||a},_lock:function(){var a=parseInt(this.score.val(),10),a=a?b._getHint.call(this,a):this.opt.noRatedMsg;c(this).data("readonly",!0).css("cursor","").attr("title",a);this.score.attr("readonly","readonly");this.stars.attr("title",a);this.cancel&&this.cancel.hide()},_roundStars:function(a){var b=(a-Math.floor(a)).toFixed(2);if(b>this.opt.round.down){var c="starOn";this.opt.halfShow&&b<this.opt.round.up?c="starHalf":b<this.opt.round.full&&(c="starOff");this.stars.eq(Math.ceil(a)-
1).attr("src",this.opt.path+this.opt[c])}},_target:function(a,d){if(this.opt.target){var f=c(this.opt.target);0===f.length&&b._error.call(this,"Target selector invalid or missing!");0>this.opt.targetFormat.indexOf("{score}")&&b._error.call(this,'Template "{score}" missing!');var e=d&&"mouseover"==d.type;void 0===a?a=this.opt.targetText:null===a?a=e?this.opt.cancelHint:this.opt.targetText:("hint"==this.opt.targetType?a=b._getHint.call(this,Math.ceil(a)):this.opt.precision&&(a=parseFloat(a).toFixed(1)),
!e&&!this.opt.targetKeep&&(a=this.opt.targetText));a&&(a=this.opt.targetFormat.toString().replace("{score}",a));f.is(":input")?f.val(a):f.html(a)}},_unlock:function(){c(this).data("readonly",!1).css("cursor","pointer").removeAttr("title");this.score.removeAttr("readonly","readonly");for(var a=0;a<this.opt.number;a++)this.stars.eq(a).attr("title",b._getHint.call(this,a+1));this.cancel&&this.cancel.css("display","")},cancel:function(a){return this.each(function(){!0!==c(this).data("readonly")&&(b[a?
"click":"score"].call(this,null),this.score.removeAttr("value"))})},click:function(a){return c(this).each(function(){!0!==c(this).data("readonly")&&(b._apply.call(this,a),this.opt.click||b._error.call(this,'You must add the "click: function(score, evt) { }" callback.'),this.opt.click.call(this,a,{type:"click"}),b._target.call(this,a))})},destroy:function(){return c(this).each(function(){var a=c(this),b=a.data("raw");b?a.off(".raty").empty().css({cursor:b.style.cursor,width:b.style.width}).removeData("readonly"):
a.data("raw",a.clone()[0])})},getScore:function(){var a=[],b;c(this).each(function(){b=this.score.val();a.push(b?parseFloat(b):void 0)});return 1<a.length?a:a[0]},readOnly:function(a){return this.each(function(){var d=c(this);d.data("readonly")!==a&&(a?(d.off(".raty").children("img").off(".raty"),b._lock.call(this)):(b._binds.call(this),b._unlock.call(this)),d.data("readonly",a))})},reload:function(){return b.set.call(this,{})},score:function(){return arguments.length?b.setScore.apply(this,arguments):
b.getScore.call(this)},set:function(a){return this.each(function(){var b=c(this),f=b.data("settings"),f=c.extend({},f,a);b.raty(f)})},setScore:function(a){return c(this).each(function(){!0!==c(this).data("readonly")&&(b._apply.call(this,a),b._target.call(this,a))})}};c.fn.raty=function(a){if(b[a])return b[a].apply(this,Array.prototype.slice.call(arguments,1));if("object"===typeof a||!a)return b.init.apply(this,arguments);c.error("Method "+a+" does not exist!")};c.fn.raty.defaults={cancel:!1,cancelHint:"Cancel this rating!",
cancelOff:"cancel-off.png",cancelOn:"cancel-on.png",cancelPlace:"left",click:void 0,half:!1,halfShow:!0,hints:["bad","poor","regular","good","gorgeous"],iconRange:void 0,mouseout:void 0,mouseover:void 0,noRatedMsg:"Not rated yet!",number:5,numberMax:20,path:"",precision:!1,readOnly:!1,round:{down:0.25,full:0.6,up:0.76},score:void 0,scoreName:"score",single:!1,size:16,space:!0,starHalf:"star-half.png",starOff:"star-off.png",starOn:"star-on.png",target:void 0,targetFormat:"{score}",targetKeep:!1,targetText:"",
targetType:"hint",width:void 0}})(jQuery);